
import { ReportData } from '../types';

// Email configuration
export interface EmailConfig {
  to: string;
  cc?: string;
  subject: string;
  body: string;
  attachmentName?: string;
}

// Generate email content from report data
export const generateEmailContent = (data: ReportData): { subject: string; body: string } => {
  const formatDate = (dateString: string) => {
    if (!dateString) return 'N/A';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  };

  const subject = `Disinfection Report - ${data.siteName} - ${formatDate(data.serviceDate)}`;

  const body = `Dear ${data.commissionedBy || 'Client'},

Please find attached the Post-Works Disinfection Report for ${data.siteName}.

Report Summary:
---------------
Client: ${data.clientName}
Site: ${data.siteName}
Address: ${data.siteAddress}
Service Date: ${formatDate(data.serviceDate)}
Job Type: ${data.jobType === 'Tank' ? 'Cold Water Storage Tank Disinfection' : 'Pipework Disinfection'}

Process Details:
- Disinfectant: ${data.disinfectant}
- Concentration: ${data.concentrationTarget} PPM
- Contact Time: ${data.contactTime}
- Technician: ${data.technicianName}

${data.testPoints.length > 0 ? `Test Points Recorded: ${data.testPoints.length}` : ''}
${data.tanks.length > 0 ? `Tanks Disinfected: ${data.tanks.length}` : ''}

The disinfection was carried out in accordance with HSG 274 Part 2 and PD855468:2015 guidelines.

If you have any questions regarding this report, please don't hesitate to contact us.

Kind regards,
Water Compliance Services Ltd
Tel: 0800 130 3221
Email: Info@watercompliance.co.uk
Web: www.watercompliance.co.uk

---
This email was generated by PureTank Report Generator
`;

  return { subject, body };
};

// Open mailto link (basic email - no attachments)
export const openMailto = (config: EmailConfig): void => {
  const mailtoLink = `mailto:${encodeURIComponent(config.to)}?${
    config.cc ? `cc=${encodeURIComponent(config.cc)}&` : ''
  }subject=${encodeURIComponent(config.subject)}&body=${encodeURIComponent(config.body)}`;

  window.open(mailtoLink, '_blank');
};

// Email sending via Web Share API (if available - allows attaching files)
export const shareViaWebShare = async (
  data: ReportData,
  file?: File
): Promise<boolean> => {
  if (!navigator.share) {
    return false;
  }

  const { subject, body } = generateEmailContent(data);

  try {
    const shareData: ShareData = {
      title: subject,
      text: body,
    };

    if (file && navigator.canShare && navigator.canShare({ files: [file] })) {
      shareData.files = [file];
    }

    await navigator.share(shareData);
    return true;
  } catch (error) {
    if ((error as Error).name !== 'AbortError') {
      console.error('Share failed:', error);
    }
    return false;
  }
};

// Check if Web Share API is available
export const canUseWebShare = (): boolean => {
  return typeof navigator !== 'undefined' && !!navigator.share;
};

// Check if can share files
export const canShareFiles = (): boolean => {
  return typeof navigator !== 'undefined' && !!navigator.canShare;
};

// Email provider configurations for future integration
export interface EmailProviderConfig {
  provider: 'emailjs' | 'sendgrid' | 'custom';
  apiKey?: string;
  serviceId?: string;
  templateId?: string;
  endpoint?: string;
}

// Placeholder for future email API integration
export const sendViaEmailProvider = async (
  config: EmailProviderConfig,
  emailConfig: EmailConfig,
  attachmentBase64?: string
): Promise<{ success: boolean; message: string }> => {
  // This is a placeholder for future email API integration
  // You would implement actual API calls here based on the provider

  console.log('Email provider integration not configured:', {
    provider: config.provider,
    to: emailConfig.to,
    subject: emailConfig.subject,
  });

  return {
    success: false,
    message: 'Email provider not configured. Use mailto or Web Share instead.',
  };
};

// Generate HTML report for email attachment
export const generateEmailHtmlReport = (data: ReportData): string => {
  const formatDate = (dateString: string) => {
    if (!dateString) return 'N/A';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  };

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Disinfection Report - ${data.siteName}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #0070c0; }
    h2 { color: #1a237e; border-bottom: 2px solid #0070c0; padding-bottom: 5px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
    th { background-color: #f0f0f0; }
    .summary { background-color: #f9f9f9; padding: 15px; border-radius: 8px; }
  </style>
</head>
<body>
  <h1>Water Compliance Services Ltd</h1>
  <h2>${data.jobType === 'Tank' ? 'Cold Water Storage Tank' : 'Pipework'} Disinfection Report</h2>

  <div class="summary">
    <p><strong>Client:</strong> ${data.clientName}</p>
    <p><strong>Site:</strong> ${data.siteName}</p>
    <p><strong>Address:</strong> ${data.siteAddress}</p>
    <p><strong>Service Date:</strong> ${formatDate(data.serviceDate)}</p>
    <p><strong>Technician:</strong> ${data.technicianName}</p>
  </div>

  <h2>Process Details</h2>
  <table>
    <tr><th>Parameter</th><th>Value</th></tr>
    <tr><td>Disinfectant</td><td>${data.disinfectant}</td></tr>
    <tr><td>Concentration Target</td><td>${data.concentrationTarget} PPM</td></tr>
    <tr><td>Contact Time</td><td>${data.contactTime}</td></tr>
    <tr><td>System Volume</td><td>${data.systemVolume} Litres</td></tr>
    <tr><td>Amount Added</td><td>${data.amountAdded}</td></tr>
  </table>

  ${data.testPoints.length > 0 ? `
  <h2>Test Point Results</h2>
  <table>
    <tr>
      <th>Location</th>
      <th>Initial PPM</th>
      <th>30 Min PPM</th>
      <th>1 Hour PPM</th>
    </tr>
    ${data.testPoints.map(tp => `
    <tr>
      <td>${tp.location}</td>
      <td>${tp.initialPpm}</td>
      <td>${tp.midPpm}</td>
      <td>${tp.finalPpm}</td>
    </tr>
    `).join('')}
  </table>
  ` : ''}

  <h2>Comments</h2>
  <p>${data.comments || 'No additional comments.'}</p>

  <hr>
  <p style="font-size: 12px; color: #666;">
    This report was carried out in accordance with HSG 274 Part 2 and PD855468:2015 guidelines.<br>
    Water Compliance Services Ltd | Tel: 0800 130 3221 | Email: Info@watercompliance.co.uk
  </p>
</body>
</html>
  `.trim();
};
